<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInita671d066ba2c27ef705889ad504b7d40
{
    public static $files = array (
        'decc78cc4436b1292c6c0d151b19445c' => __DIR__ . '/..' . '/phpseclib/phpseclib/phpseclib/bootstrap.php',
    );

    public static $prefixLengthsPsr4 = array (
        'p' => 
        array (
            'phpseclib\\' => 10,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'phpseclib\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpseclib/phpseclib/phpseclib',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInita671d066ba2c27ef705889ad504b7d40::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInita671d066ba2c27ef705889ad504b7d40::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
